import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const plusJakartaSans = localFont({
  src: [
    {
      path: './fonts/PlusJakartaSans[wght].ttf',
      style: 'normal',
    },
    {
      path: './fonts/PlusJakartaSans-Italic[wght].ttf',
      style: 'italic',
    },
  ],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Climate Solutions Conference',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>{children}</body>
    </html>
  )
}
